import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "UI/UX Designer",
    company: "Jenoss",
    logo: "/images/careers/jenoss.png",
    location: "Thanh Xuan, Ha Noi, Viet Nam",
    location_type: "Onsite",
    type: "Full time",
    start_date: "2024-12",
    end_date: "2025-09",
    industry: "Thương mại điện tử (E-commerce)",
    link: "https://jenoss.com/",
    responsibilities: [
    "Designed and optimized UI/UX for Jenoss and multiple e-commerce websites including jenoss.com, mayartcraft.com, and peace-blend.com.",
    "Created responsive, user-friendly interfaces using Figma, ensuring consistency with brand identity and design system.",
    "Conducted user research and prototyping to enhance shopping experience and improve conversion rates.",
    "Collaborated closely with development and marketing teams to deliver visually appealing, high-performing web pages.",
    ],
    isShow: true,
  },
  {
    position: "UI/UX Designer",
    company: "SAPP Academy",
    logo: "/images/careers/sapp academy.png",
    location: "Le Thanh Nghi, Hai Ba Trung, Ha Noi, Viet Nam",
    location_type: "Onsite",
    type: "Full time",
    start_date: "2024-04",
    end_date: "2024-12",
    industry: "Học viện đào tạo (Education)",
    link: "https://sapp.edu.vn/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    isShow: true,
  },
  {
    position: "UI/UX Designer",
    company: "SAPP Academy",
    logo: "/images/careers/sapp academy.png",
    location: "Le Thanh Nghi, Hai Ba Trung, Ha Noi, Viet Nam",
    location_type: "Onsite",
    type: "Full time",
    start_date: "2024-04",
    end_date: "2024-12",
    industry: "Học viện đào tạo (Education)",
    link: "https://sapp.edu.vn/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    isShow: true,
  },
  {
    position: "UI/UX Designer",
    company: "SAPP Academy",
    logo: "/images/careers/sapp academy.png",
    location: "Le Thanh Nghi, Hai Ba Trung, Ha Noi, Viet Nam",
    location_type: "Onsite",
    type: "Full time",
    start_date: "2024-04",
    end_date: "2024-12",
    industry: "Học viện đào tạo (Education)",
    link: "https://sapp.edu.vn/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    isShow: true,
  },
  {
    position: "UI/UX Designer",
    company: "SAPP Academy",
    logo: "/images/careers/sapp academy.png",
    location: "Le Thanh Nghi, Hai Ba Trung, Ha Noi, Viet Nam",
    location_type: "Onsite",
    type: "Full time",
    start_date: "2024-04",
    end_date: "2024-12",
    industry: "Học viện đào tạo (Education)",
    link: "https://sapp.edu.vn/",
    responsibilities: [
      "Developed a responsive and interactive landing page using Next.js to promote company services and solutions.",
      "Ensured SEO optimization and fast performance by leveraging Next.js features such as static site generation.",
      "Collaborated with design and marketing teams to align web presence with brand identity.",
    ],
    isShow: true,
  },
];
